controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

#index: (nom de la route)
#  path: / (chemin dans l'url de la route)
#  controller: App\Controller\DefaultController:index (fonction avec le chemin du controller qui est assiciée à cette route)

admin_product_list:
  path: /admin/products
  controller: App\Controller\Admin\AdminProductController::adminProductList

admin_product_show:
  path: /admin/product/{id}
  controller: App\Controller\Admin\AdminProductController::adminProductShow

admin_product_create:
  path: /admin/create/product
  controller: App\Controller\Admin\AdminProductController::adminCreateProduct

admin_product_update:
  path: /{id}/update
  controller: App\Controller\Admin\AdminProductController::adminProductUpdate

admin_product_delete:
  path: /delete/product/{id}
  controller: App\Controller\Admin\AdminProductController::adminDeleteProduct

admin_list_category:
  path: /admin/categories
  controller: App\Controller\Admin\AdminCategoryController::listCategory

admin_show_category:
  path: /admin/category/{id}
  controller: App\Controller\Admin\AdminCategoryController::showCategory

admin_create_category:
  path: /admin/create/category
  controller: App\Controller\Admin\AdminCategoryController::createCategory

admin_update_category:
  path: /admin/update/category/{id}
  controller: App\Controller\Admin\AdminCategoryController::updateCategory

admin_delete_category:
  path: /admin/delete/category/{id}
  controller: App\Controller\Admin\AdminCategoryController::deleteCategory
